services:
  fastapi:
    build:
      context: .  # 指向 Dockerfile 所在目錄
      dockerfile: Dockerfile
    image: n8n_fastapi # 指定映像名稱
    container_name: fastapi-server
    volumes:
      - ${N8N_DATA_PATH}/etf_data:/mnt/etf_data  # 將N8N_DATA_PATH路徑目錄掛載到容器內
      - ./src:/app  # 將./src載到容器內的/app，方便修改程式碼後不需要重建映像
    ports:
      - "${FASTAPI_PORT:-8000}:8000"  # 將 FastAPI 的 8000 端口映射到主機
    networks:
      - app_network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "${N8N_PORT:-5678}:5678"  # 將 n8n 的 5678 端口映射到主機
    volumes:
      - ${N8N_DATA_PATH}:/home/node/.n8n  # 將N8N_DATA_PATH路徑目錄掛載到容器內
    environment:
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true  # 開啟n8n社群工具下載
      - GENERIC_TIMEZONE=Asia/Taipei  # 設定時區
    networks:
      - app_network

networks:
  app_network:
    driver: bridge